{"name": "用例8：主播端查看观众端发言", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\pgk bqt\\\\PycharmProjects\\\\Chamet_project\\\\common/screenshots/party_ten/party_ten_2023-06-26 11_17_07.png'", "trace": "self = <test_case.test_10party_mult.Test_multchamet object at 0x000002160B9A8910>\n\n    @allure.severity(allure.severity_level.BLOCKER)\n    @allure.title('用例8：主播端查看观众端发言')\n    def test_TenParty_008(self):\n        logging.info('===用例8：主播端查看观众端发言===')\n        try:\n>           anchor_chat_area = self.multanchor.chat_area(-1)\n\ntest_10party_mult.py:173: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <common.partytencommon.multparty_ten_anchor.Multanchor object at 0x000002160B9C2710>, num1 = -1\n\n    def chat_area(self,num1):\n        logging.info('===消息内容===')\n        chat = self.driver.find_elements(MobileBy.ID, \"com.hkfuliao.chamet:id/contentTv\")\n>       chat_content = chat[num1].text\nE       IndexError: list index out of range\n\n..\\common\\partytencommon\\multparty_ten_anchor.py:149: IndexError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_case.test_10party_mult.Test_multchamet object at 0x000002160B9A8910>\n\n    @allure.severity(allure.severity_level.BLOCKER)\n    @allure.title('用例8：主播端查看观众端发言')\n    def test_TenParty_008(self):\n        logging.info('===用例8：主播端查看观众端发言===')\n        try:\n            anchor_chat_area = self.multanchor.chat_area(-1)\n            assert anchor_chat_area == \"hi\"\n            logging.info('===断言成功，主播端可看到观众端发言===')\n        except AssertionError as e:\n            logging.info('===断言失败===')\n            screen_name = self.multanchor.screenshot('party_ten')\n            logging.info(f'截图成功，图片为{screen_name}')\n            raise\n        except:\n            logging.info(\"===执行失败===\")\n>           screen_name = self.multanchor.screenshot('party_ten')\n\ntest_10party_mult.py:183: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <common.partytencommon.multparty_ten_anchor.Multanchor object at 0x000002160B9C2710>, module = 'party_ten'\n\n    def screenshot(self, module):\n        time = self.getTime()\n        image_file = os.path.dirname(os.path.dirname(__file__)) + '/screenshots/party_ten/%s_%s.png' % (module, time)\n        self.driver.get_screenshot_as_file(image_file)\n>       with open(image_file, mode='rb') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\pgk bqt\\\\PycharmProjects\\\\Chamet_project\\\\common/screenshots/party_ten/party_ten_2023-06-26 11_17_07.png'\n\n..\\common\\partytencommon\\multparty_ten_anchor.py:76: FileNotFoundError"}, "attachments": [{"name": "log", "source": "6a325736-b64b-40e6-95e0-3f84bfa97fb0-attachment.txt", "type": "text/plain"}], "start": 1687749417595, "stop": 1687749428444, "uuid": "b433cdf1-a527-4278-9c78-1aa7e77c2925", "historyId": "fe51202748bda08a9f04ccb195600e70", "testCaseId": "fe51202748bda08a9f04ccb195600e70", "fullName": "test_10party_mult.Test_multchamet#test_TenParty_008", "labels": [{"name": "severity", "value": "blocker"}, {"name": "suite", "value": "test_10party_mult"}, {"name": "subSuite", "value": "Test_multchamet"}, {"name": "host", "value": "DESKTOP-8OL56K6"}, {"name": "thread", "value": "2064-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_10party_mult"}]}