{"uuid": "431b55b5-b860-4b93-9275-812151c062ab", "children": ["2d46a090-c714-4d1f-8322-cf220413db51", "706df34b-ec21-4d2f-a18c-f32dc36232c3", "23f17415-bf6e-4ecf-99b5-0afb57c7a302", "70bd6b45-ba36-433d-861e-c48e8974e4c3", "efd4011d-4661-45ec-825b-129cf83578b8", "66b2a0e0-46ac-4c90-a617-b0c869dd1308", "cbdd44c2-f9b9-4054-85b0-49107becef71", "a01c564b-a2ce-4347-83c5-df70e4eeec44", "52fe640e-4a48-44c2-8418-fae4397dda2b", "f204141a-ea44-493e-b459-966bffb29ca5", "4f37f8ce-2032-41cb-9e24-86c6f48e2a9d", "e38e441f-a7fa-4c45-aec3-d7372d63258b", "a7cd9f90-2f81-4fa1-9417-55c03c28226e", "8cb219ec-45ce-4b4b-b2c9-e5736a51f468", "5d0073fa-96cc-4dfe-8ae8-563475d1331c", "a12981e4-3f22-4b74-a639-478ef7625498", "30d8c58a-81c7-40ad-bcb5-9dab9d7057e5", "c6dc44e4-f5bf-4509-86bc-8157e52d518a", "337357fb-9c1e-4ea3-a40d-e235ee762220", "bc4c1865-0808-4347-8c5f-5daa4b8774d7", "4eab1264-4f86-4f3a-8e01-624595b53392", "dce978ec-d284-4d8c-88ea-ad6e3d9f0c19", "a1592cb7-61fa-423b-9c0a-341f86664541", "3a212010-0f04-4a48-8c53-9d2a3800b4d4", "5c4aa26d-3c6c-45aa-a980-7f7eb1cf9245", "bfc913f4-f76f-46dc-9752-bf32a8020df0", "bcf12e39-3534-41bb-9773-e34e13973374", "88e24eb3-391c-43c6-a8e8-b8b4d97490c0", "82155d3e-0ec9-413d-b07c-8e58b95dc6d6", "6d2b9ecd-b4df-4c28-8197-0d5057c142ab", "7701fdcd-8e24-4da4-ac23-62630db3dec9", "b37df8c3-f311-4bc1-934f-44579ee36dcc", "21a18c14-7d1a-41c1-aa65-c86b2b4d4a1e", "dba1be01-ca9a-45de-80cc-60652f73edd1", "47a24dcf-4f32-4c51-9dda-2f00a1075adb", "d4475877-2981-4f5f-af8e-1f28b4d92f09", "77393543-3c46-41cd-8843-77eca032b853", "928e78bb-9917-42ee-9611-2961e444d1aa", "ca972a7a-50ae-40aa-ab86-f6cf97e68613", "5a26aec4-5eef-4b78-bb37-f3ddd3b445a0", "1b887740-d543-4e41-bd6f-233a3136c1e3", "80ae813c-3508-425b-b2a1-f64a91a575db", "40b21909-e60a-4feb-9b69-458554d9627c", "50033a72-637a-4cd8-884a-eb8364099790", "2921bed5-769d-4812-ad45-75c1a9c89c6d", "273676b3-461d-48c4-a382-cbf4ca9edfaf", "136a080a-4e59-4709-9d9f-23abc4c66688"], "befores": [{"name": "_xunit_setup_class_fixture_Test_multchamet", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Device 832c16a4 was not in the list of connected devices\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Device 832c16a4 was not in the list of connected devices\n    at getResponseForW3CError (C:\\Users\\pgk bqt\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (C:\\Users\\pgk bqt\\AppData\\Local\\Programs\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)\n", "trace": "  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\python.py\", line 864, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\python.py\", line 785, in _call_with_optional_argument\n    func(arg)\n  File \"C:\\Users\\pgk bqt\\PycharmProjects\\Chamet_project\\common\\partytencommon\\multparty_star_end.py\", line 17, in setup_class\n    self.audiencedriver=audience_appium_desired()\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\pgk bqt\\PycharmProjects\\Chamet_project\\common\\partytencommon\\audience_desired_caps.py\", line 33, in audience_appium_desired\n    driver = webdriver.Remote('http://localhost' + \":\" + str(data['audience_port']) + '/wd/hub', desired_caps2)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 234, in __init__\n    super().__init__(\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 324, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1689133457526, "stop": 1689133492051}], "start": 1689133457526, "stop": 1689133494903}