{"uuid": "46442bda-8467-422c-9c31-b644d3599124", "children": ["1877a9bc-fcf4-442f-bdc2-8c0883c083ad", "ec877f0b-2e18-4f0d-90b2-ab4bae72f29a", "1143b9a0-851a-4fe3-8401-91ac0af7d71e", "edd5a6aa-4432-4508-9c2d-a1502a1aceab", "4a633f3a-c3b7-4624-8aaf-034bd1f9ff38", "142a4c46-5ea0-4402-a52e-51e4194a8ba5", "bfb1df84-842b-4276-a8dc-77a306bc8940", "63f05307-da2a-4027-9f7d-7ea40619e0be", "21f36fef-f512-4216-bb87-c68237822657", "2fc855da-0816-402f-a955-479e906758c6", "ddd44434-84c5-456b-ad57-1a3b735a7ee9", "d0d36456-a204-4a28-907d-62edd9aa23d1", "12539dbc-dd92-48fc-b8c0-2505759a405b", "f099edda-6aa5-4601-9fd6-cf53567fa430", "3df050c6-b558-4ea9-9e69-151f694fbfe1", "40f496f2-fbfc-4cf7-8886-cc84fdc8aa2c", "55d37768-4444-47d2-a727-946e6a096030", "e40a8137-5981-4f93-824c-f4e1a76345fe", "49dd4d16-77e8-4f2d-83e8-f35cb880cf9d", "20f40abe-1d94-40f0-bbbe-48796b4727db", "f52bc1bd-c526-4918-b6e9-610a1a056acc", "c4b037e5-f4f3-4258-9163-0c4f8a59e3ae", "041a3cc3-5ad1-4513-975e-ce914af84e75", "9338ae50-6aea-493e-8cec-2a5222173efd", "c6d766c2-e6a5-4464-a18b-59814769c9ef"], "befores": [{"name": "_xunit_setup_class_fixture_Test_multchamet", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4726): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002B78BA9AB50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))\n", "trace": "  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\python.py\", line 864, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\_pytest\\python.py\", line 785, in _call_with_optional_argument\n    func(arg)\n  File \"C:\\Users\\pgk bqt\\PycharmProjects\\Chamet_project\\common\\partytencommon\\multparty_star_end.py\", line 11, in setup_class\n    self.anchordriver=anchor_appium_desired()\n                      ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\pgk bqt\\PycharmProjects\\Chamet_project\\common\\partytencommon\\anchor_desired_caps.py\", line 33, in anchor_appium_desired\n    driver = webdriver.Remote('http://localhost' + \":\" + str(data['anchor_port']) + '/wd/hub', desired_caps1)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 234, in __init__\n    super().__init__(\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 324, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 438, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\request.py\", line 78, in request\n    return self.request_encode_body(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"E:\\pycharm_file\\Chamet_project\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1688378960791, "stop": 1688378977679}], "start": 1688378960791, "stop": 1688378984298}