{"name": "用例4：观众进入10人交友房", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\pgk bqt\\\\PycharmProjects\\\\Chamet_project\\\\common/screenshots/party_ten/party_ten_2023-06-26 13_36_47.png'", "trace": "self = <test_case.test_10party_mult.Test_multchamet object at 0x00000228C0966F10>\n\n    @allure.severity(allure.severity_level.BLOCKER)\n    @allure.title('用例4：观众进入10人交友房')\n    def test_TenParty_004(self):\n        logging.info('===用例4：观众进入10人交友房===')\n        try:\n            # audienceeparty_Start_End.setup_class(self)\n            self.multaudience.audience_party_tab_Btn()\n            party_list_num = self.multaudience.party_list()\n            if party_list_num == 0:\n                pytest.skip(\"没有交友房，跳过该测试用例\")\n            party_username = self.multaudience.audience_enter_tenparty(self.which_party)\n>           assert party_username == self.multaudience.party_title()\nE           AssertionError: assert 'User20113007' == ''\nE             + User20113007\n\ntest_10party_mult.py:90: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_case.test_10party_mult.Test_multchamet object at 0x00000228C0966F10>\n\n    @allure.severity(allure.severity_level.BLOCKER)\n    @allure.title('用例4：观众进入10人交友房')\n    def test_TenParty_004(self):\n        logging.info('===用例4：观众进入10人交友房===')\n        try:\n            # audienceeparty_Start_End.setup_class(self)\n            self.multaudience.audience_party_tab_Btn()\n            party_list_num = self.multaudience.party_list()\n            if party_list_num == 0:\n                pytest.skip(\"没有交友房，跳过该测试用例\")\n            party_username = self.multaudience.audience_enter_tenparty(self.which_party)\n            assert party_username == self.multaudience.party_title()\n            logging.info('===断言成功，成功进入10人交友房===')\n        except AssertionError as e:\n            logging.info('===断言失败===')\n>           screen_name = self.multaudience.screenshot('party_ten')\n\ntest_10party_mult.py:94: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <common.partytencommon.multparty_ten_audience.Multaudience object at 0x00000228C0996BD0>, module = 'party_ten'\n\n    def screenshot(self, module):\n        time = self.getTime()\n        image_file = os.path.dirname(os.path.dirname(__file__)) + '/screenshots/party_ten/%s_%s.png' % (module, time)\n        self.driver.get_screenshot_as_file(image_file)\n>       with open(image_file, mode='rb') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\pgk bqt\\\\PycharmProjects\\\\Chamet_project\\\\common/screenshots/party_ten/party_ten_2023-06-26 13_36_47.png'\n\n..\\common\\partytencommon\\multparty_ten_audience.py:76: FileNotFoundError"}, "attachments": [{"name": "log", "source": "6aa2abd4-f3f2-4993-9517-78e43c802723-attachment.txt", "type": "text/plain"}], "start": 1687757797190, "stop": 1687757807879, "uuid": "a7ed396b-7dde-480f-9374-7c291c6601c6", "historyId": "6e51666f221649e45249df6a775dfc4b", "testCaseId": "6e51666f221649e45249df6a775dfc4b", "fullName": "test_10party_mult.Test_multchamet#test_TenParty_004", "labels": [{"name": "severity", "value": "blocker"}, {"name": "suite", "value": "test_10party_mult"}, {"name": "subSuite", "value": "Test_multchamet"}, {"name": "host", "value": "DESKTOP-8OL56K6"}, {"name": "thread", "value": "2164-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_10party_mult"}]}